basePath: /v1
definitions:
  dto.Dealer:
    properties:
      name:
        type: string
    type: object
  dto.Last20Results:
    properties:
      color:
        type: string
      gameId:
        type: string
      powerUpList:
        items: { }
        type: array
      powerUpMultipliers:
        items: { }
        type: array
      result:
        type: integer
      time:
        type: string
    type: object
  dto.PragmaticTable:
    properties:
      currency:
        type: string
      dealer:
        $ref: '#/definitions/dto.Dealer'
      languageSpecificTableInfo:
        type: string
      last20Results:
        items:
          $ref: '#/definitions/dto.Last20Results'
        type: array
      newTable:
        type: boolean
      tableId:
        type: string
      tableImage:
        type: string
      tableLimits:
        $ref: '#/definitions/dto.TableLimits'
      tableName:
        type: string
      tableOpen:
        type: boolean
      tableSubtype:
        type: string
      tableType:
        type: string
      totalSeatedPlayers:
        type: integer
    type: object
  dto.PragmaticTableWithID:
    properties:
      pragmaticTable:
        $ref: '#/definitions/dto.PragmaticTable'
      tableAndCurrencyID:
        description: tID = 100; cID = 200 => TableAndCurrencyID = "100:200"
        type: string
    type: object
  dto.TableLimits:
    properties:
      maxBet:
        type: number
      maxPlayers:
        type: integer
      minBet:
        type: number
      ranges:
        items:
          type: number
        type: array
    type: object
  server.envelope:
    type: object
  server.envelopeHealthCheck:
    properties:
      status:
        type: string
      system_info:
        $ref: '#/definitions/server.systemInfo'
    type: object
  server.systemInfo:
    properties:
      version:
        type: string
    type: object
host: localhost:8080
info:
  contact: { }
  title: Pragmatic Live Feed Aggregator API Documentation
  version: 1.0.0
paths:
  /healthcheck:
    get:
      consumes:
        - application/json
      description: Check if the service is up
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.envelopeHealthCheck'
      summary: Check if the service is up
  /tables:
    get:
      consumes:
        - application/json
      description: List Pragmatic live feed tables data
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/server.envelope'
              - properties:
                  data:
                    items:
                      $ref: '#/definitions/dto.PragmaticTableWithID'
                    type: array
                type: object
      summary: List Pragmatic live feed tables data
swagger: "2.0"
