// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	dto "github.com/dsha256/plfa/pkg/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddTable mocks base method.
func (m *MockRepository) AddTable(table dto.PragmaticTable) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddTable", table)
}

// AddTable indicates an expected call of AddTable.
func (mr *MockRepositoryMockRecorder) AddTable(table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTable", reflect.TypeOf((*MockRepository)(nil).AddTable), table)
}

// ListTables mocks base method.
func (m *MockRepository) ListTables() ([]dto.PragmaticTableWithID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTables")
	ret0, _ := ret[0].([]dto.PragmaticTableWithID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTables indicates an expected call of ListTables.
func (mr *MockRepositoryMockRecorder) ListTables() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTables", reflect.TypeOf((*MockRepository)(nil).ListTables))
}

// MockAggregateRepository is a mock of AggregateRepository interface.
type MockAggregateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAggregateRepositoryMockRecorder
}

// MockAggregateRepositoryMockRecorder is the mock recorder for MockAggregateRepository.
type MockAggregateRepositoryMockRecorder struct {
	mock *MockAggregateRepository
}

// NewMockAggregateRepository creates a new mock instance.
func NewMockAggregateRepository(ctrl *gomock.Controller) *MockAggregateRepository {
	mock := &MockAggregateRepository{ctrl: ctrl}
	mock.recorder = &MockAggregateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregateRepository) EXPECT() *MockAggregateRepositoryMockRecorder {
	return m.recorder
}

// AddTable mocks base method.
func (m *MockAggregateRepository) AddTable(table dto.PragmaticTable) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddTable", table)
}

// AddTable indicates an expected call of AddTable.
func (mr *MockAggregateRepositoryMockRecorder) AddTable(table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTable", reflect.TypeOf((*MockAggregateRepository)(nil).AddTable), table)
}

// ListTables mocks base method.
func (m *MockAggregateRepository) ListTables() ([]dto.PragmaticTableWithID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTables")
	ret0, _ := ret[0].([]dto.PragmaticTableWithID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTables indicates an expected call of ListTables.
func (mr *MockAggregateRepositoryMockRecorder) ListTables() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTables", reflect.TypeOf((*MockAggregateRepository)(nil).ListTables))
}
